### ISSUE TITLE
[Help] 后端地址是如何获取的

### ISSUE THREAD

**Issue by Nick8626** [OXeu/Rin#103]
接入 Github OAuth这部分，后端地址是从哪里获取的？目前是卡到这里了

**Comment by OXeu** [comment]
如果是使用默认的 workers 地址的话是后面部署完成之才能再获取的，如果你要绑定一个域名的话就是你绑定的域名的地址，但是这个可以先随便填占位置，后面等后端部署好了再回来修改

**Comment by Nick8626** [comment]
地址现在获取到了，自定义域。只是workers哪里没有设置好，不知该如何设置。目前页面可以打开，但是登录无效，没有回调成功

**Comment by OXeu** [comment]
> WORKER_NAME: Nicker
> ...
> Expected "name" to be of type string, alphanumeric and lowercase with dashes only but got "Nicker".

WORKER_NAME 应该是全小写

**Comment by paulloo** [comment]
有没有遇到cors 跨域的问题？

**Comment by OXeu** [comment]
> 有没有遇到cors 跨域的问题？

有新问题的话请新开一个 issue 详细描述一下

**Comment by Nick8626** [comment]
> > WORKER_NAME：尼克......预期的“name”类型为字符串、字母数字和小写，仅带破折号，但得到“Nicker”。
> 
> WORKER_NAME 应该是全小写

已改为小写，现在git登录提示：404：没有这样的页面！

**Comment by OXeu** [comment]
请检查 GitHub OAuth 配置的回调地址是否是自己的后端地址，具体参见 #632024年6月13日 10:00，Nick8626 ***@***.***>写道：


WORKER_NAME：尼克......预期的“name”类型为字符串、字母数字和小写，仅带破折号，但得到“Nicker”。

WORKER_NAME 应该是全小写

已改为小写，现在git登录提示：404：没有这样的页面！

**Comment by paulloo** [comment]
> > 有没有遇到cors 跨域的问题？
> 
> 有新问题的话请新开一个 issue 详细描述一下

https://github.com/OXeu/Rin/issues/116
麻烦请教一下！

**Comment by Nick8626** [comment]
> 请检查 GitHub OAuth 配置的回调地址是否是自己的后端地址，具体参见 #63

回调地址是后端地址。我觉得是CFWorkers没设置好，只是创建了，无内容。

**Comment by Nick8626** [comment]
> 请检查 GitHub OAuth 配置的回调地址是否是自己的后端地址，具体参见 #63

2024-06-13T03:22:47.5363376Z error: No matching version for workspace dependency "rin-server". Version: "workspace:../server"

目前最新是工作流报错，但是我已在变量中将值改为了 nicker-server

**Comment by OXeu** [comment]
> > 请检查 GitHub OAuth 配置的回调地址是否是自己的后端地址，具体参见 #63
> 
> 2024-06-13T03:22:47.5363376Z error: No matching version for workspace dependency "rin-server". Version: "workspace:../server"
> 
> 目前最新是工作流报错，但是我已在变量中将值改为了 nicker-server

重新同步一下最新的分支

**Comment by Nick8626** [comment]
> > > 请检查 GitHub OAuth 配置的回调地址是否是自己的后端地址，具体参见 #63
> > 
> > 
> > 2024-06-13T03：22：47.5363376Z 错误：工作区依赖项“rin-server”没有匹配的版本。版本： “workspace：../服务器”
> > 目前最新是工作流报错，但是我已在变量中将值改为了 nicker-server
> 
> 重新同步一下最新的分支，这是由于昨天 Bun 发布了新的版本，之前的代码中的配置写法不能用了

已同步最新分支，并且工作流部署成功。但是后端回调CFworkers报错 Error 1101，CFworkers里报错28个。

https://s-n.nicker.cc//user/github

**Comment by OXeu** [comment]
1101 参见 #42
同时你给出的域名包含两个 //，检查一下 前端的 API_URL 是否末尾存在 “/” 如果是需要去掉并重新部署一次

**Comment by Nick8626** [comment]
> 1101 参见 #42 同时你给出的域名包含两个 //，检查一下 前端的 API_URL 是否末尾存在 “/” 如果是需要去掉并重新部署一次

JWT_SECRET=<JWT 认证所需密钥，可为常规格式的任意密码>

这个变量是否需要在CFWORKERS中同步设置？地址问题已重新部署，JWT已添加，目前还是1101

**Comment by Nick8626** [comment]
已部署成功，感谢

**Comment by OXeu** [comment]
> > 1101 参见 #42 同时你给出的域名包含两个 //，检查一下 前端的 API_URL 是否末尾存在 “/” 如果是需要去掉并重新部署一次
> 
> JWT_SECRET=<JWT 认证所需密钥，可为常规格式的任意密码>
> 
> 这个变量是否需要在CFWORKERS中同步设置？地址问题已重新部署，JWT已添加，目前还是1101

在 GitHub 中配置好以后部署的时候是会自动上传同步到 Cloudflare 的，如果你在 Cloudflare 没有看到这个环境变量说明 GitHub 的环境变量配置是有问题的
