### ISSUE TITLE
[Help] 启动开发服务器出现D1_ERROR: no such table

### ISSUE THREAD

**Issue by GrahLnn** [OXeu/Rin#108]
**描述你遇到的问题**

根据contributing文档配置了相关变量，也设置了[[d1_databases]]，并且cf里也创好了相关的表，但启动开发服务器访问端点都出现D1_ERROR: no such table

**复现步骤**

**期望行为**

**截图**

![image](https://github.com/OXeu/Rin/assets/67181515/e02d4e4f-d3e7-4ab8-85a1-1466978dfefc)

**额外信息**

**Comment by OXeu** [comment]
抱歉，文档里面忘记更新了，在此之前还需要执行数据库迁移创建数据表才能使用，大概的命令是，具体可以参照`scripts/migrator.ts` 和 Wrangler 的文档
```
bunx wrangler d1 execute rin --local --file ./server/sql/0000.sql
```
