### ISSUE TITLE
[Help] 怎么去掉朋友们

### ISSUE THREAD

**Issue by IAn2018cs** [OXeu/Rin#109]
<img width="358" alt="image" src="https://github.com/OXeu/Rin/assets/18318073/c837ec03-2b9e-4cc0-b609-088a5aec49d4">
想去掉这个 tab，应该怎么设置

**Comment by OXeu** [comment]
目前不支持通过配置关闭，但是可以注释掉以下两行隐藏该按钮
https://github.com/OXeu/Rin/blob/main/client%2Fsrc%2Fcomponents%2Fheader.tsx#L47-L47

https://github.com/OXeu/Rin/blob/main/client%2Fsrc%2Fcomponents%2Fheader.tsx#L133
