### ISSUE TITLE
[Feature Request] Can it displays the number of visits?

### ISSUE THREAD

**Issue by yixian3500** [OXeu/Rin#114]
**描述您想要的解决方案**
在页面和文章列表显示访问量等信息

顺便感谢这个优秀的项目

**Comment by OXeu** [comment]
已加入计划列表

**Comment by SliverKeigo** [comment]
[Webviso：基于Clouflare+D1的web访客统计服务](https://github.com/yestool/analytics_with_cloudflare)

**Comment by SliverKeigo** [comment]
> 已加入计划列表

[Webviso：基于Clouflare+D1的web访客统计服务](https://github.com/yestool/analytics_with_cloudflare)
