### ISSUE TITLE
[Bug] 上传图片 Access Denied

### ISSUE THREAD

**Issue by Jackchen0514** [OXeu/Rin#115]
**Bug 描述**
上传图片的时候，我看调用了 API_URL 如 https://rin-server.xxxxx.workers.dev/storage 这个接口， 报400 Access Denied错误，然后又调用一次，204 No Content

**Comment by OXeu** [comment]
请问有浏览器 F12 查看请求响应结果的截图吗？

另外麻烦在 Cloudflare 控制面板中看一下 R2 存储桶中是否成功上传了

**Comment by Jackchen0514** [comment]
![image](https://github.com/OXeu/Rin/assets/38276126/f2effaaf-c4a0-4ef5-99a0-ed8b09ded5ea)

**Comment by Jackchen0514** [comment]
![image](https://github.com/OXeu/Rin/assets/38276126/71ec2f10-dee0-444f-9715-1137b95d641a)

**Comment by OXeu** [comment]
> ![image](https://private-user-images.githubusercontent.com/38276126/339030287-f2effaaf-c4a0-4ef5-99a0-ed8b09ded5ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDU3MzEsIm5iZiI6MTcxODIwNTQzMSwicGF0aCI6Ii8zODI3NjEyNi8zMzkwMzAyODctZjJlZmZhYWYtYzRhMC00ZWY1LTk5YTAtZWQ4YjA5ZGVkNWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMWVhNjcxYjE2Y2Y1YTBkYmVjZGM4NzdiYzc1MTNmYWE5ZDFjY2M5MDdiYWZhMGU3NjEwZTA0NjcxNGUxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aH4nREWYBdEeXrJf2Ll1tBlvIcY2iD5IOagbiD5SHDY)

可以看下 Response 的有值吗

**Comment by Jackchen0514** [comment]
![image](https://github.com/OXeu/Rin/assets/38276126/62d368c8-1d45-4705-98e7-f1069ab4ebac)

**Comment by OXeu** [comment]
看样子是 `S3_ACCESS_KEY_ID` 和 `S3_SECRET_ACCESS_KEY` 设置有误或者没有给 R2 的访问权限导致的

**Comment by Jackchen0514** [comment]
好了，谢谢哈， 只给了read权限

**Comment by Jackchen0514** [comment]
上面那张带token信息图片麻烦删除下哈，麻烦了
