### ISSUE TITLE
[Help] github deploy 成功了，但是接口请求不通，报跨域，如何查看日志？

### ISSUE THREAD

**Issue by paulloo** [OXeu/Rin#116]
**worker 部署成功了，请求跨域，如何查看日志排查？**

**复现步骤**

**期望行为**

**截图**

![image](https://github.com/OXeu/Rin/assets/32083925/fabb998b-8b15-47bf-87f2-5fe5618cfb75)

**额外信息**

**Comment by OXeu** [comment]
参见 #42

**Comment by paulloo** [comment]
> 参见 #42

果然  actions 部署的时候这几个变量没带过去，我手动配了下就好了 
![image](https://github.com/OXeu/Rin/assets/32083925/4bb01d57-7867-4d94-ac2f-928727b3e6ae)

**Comment by OXeu** [comment]
> > 参见 #42
> 
> 果然  actions 部署的时候这几个变量没带过去，我手动配了下就好了 
> ![image](https://github.com/OXeu/Rin/assets/32083925/4bb01d57-7867-4d94-ac2f-928727b3e6ae)
> 

不清楚是忘了放在 GitHub 的 Secrets 还是放在了 Variables 中，要是放在 Variables 里不会上传的并且 CI 日志中会泄露你的密钥
