### ISSUE TITLE
[Help] SEO Workflow部署失败

### ISSUE THREAD

**Issue by ossssss6** [OXeu/Rin#119]
**描述你遇到的问题**
SEO Workflow部署失败
**复现步骤**
1. Actions里部署SEO Workflow部署失败 

**期望行为**
成功部署SEO Workflow，或取消部署SEO Workflow，停止给我发部署失败的Email。

**截图**
![image](https://github.com/OXeu/Rin/assets/93513538/b117401b-4f0a-4d5e-a0c2-751290a5f914)
**额外信息**

**Comment by OXeu** [comment]
是因为最近 Bun 更新新版本导致的，最新的分支已经修复了，同步一下仓库就行了

**Comment by ossssss6** [comment]
已解决，谢谢大佬！
