### ISSUE TITLE
[Help] 點擊GitHub登錄後跳轉的地址不正確

### ISSUE THREAD

**Issue by SliverKeigo** [OXeu/Rin#120]
**描述你遇到的问题**
點擊GitHub登錄後跳轉的地址不正確 在前端地址後面拼接了<后端地址>/user/github

**复现步骤**
1. xxxxx
2. xxx

**期望行为**

**截图**
![image](https://github.com/OXeu/Rin/assets/112426853/9abe78a4-a5d0-48fc-b30d-bee635935db2)

**额外信息**

**Comment by SliverKeigo** [comment]
![image](https://github.com/OXeu/Rin/assets/112426853/b54a166e-590e-4c81-9666-9673972e0740)
刪除該環境變量後成功正確跳轉

**Comment by OXeu** [comment]
有几个问题：
1. 描述中说的是跳转到了 `<前端地址>/<后端地址>/user/github/callback`，这是授权成功后回调的地址，如果这个地址出错应该见检查 Github Oauth 中配置中的地址。但是截图中的地址是 `<前端地址>/<后端地址>/user/github`，是前端跳转到后端的地址，综合考虑可能是描述的时候写错了的可能性更大
2. 前端点击登录跳转的地址拼接应该是只借助于 `OAUTH_URL` 和 `API_URL`，其中 `OAUTH_URL` 会被优先使用，如果其他请求正常的话大概率是 `OAUTH_URL` 没用添加 `https://` 的原因才产生以上现象，后面正常工作猜测是删除了 OAUTH_URL

**Comment by SliverKeigo** [comment]
OAUTH_URL 填寫正確 確實是在刪除FRONTEND_URL後成功跳轉

**Comment by SliverKeigo** [comment]
如果OAUTH_URL 未添加https://將無法保存

**Comment by OXeu** [comment]
> OAUTH_URL 填寫正確 確實是在刪除FRONTEND_URL後成功跳轉

没道理啊，OAuth 跟 FRONTEND_URL 完全不相干，是不是在这期间还同步过仓库
