### ISSUE TITLE
[Help] WORKER_NAME 是指在pages创建的rin,还是要另外在workers中创建项目？

### ISSUE THREAD

**Issue by SoMeTech** [OXeu/Rin#121]
根据部署文档，提到
“配置 GitHub Action
在自己 fork 的仓库中 > Settings > Secrets and Variables > Actions > Repository secrets 点击 New repository secret 创建以下两个密钥：

CLOUDFLARE_ACCOUNT_ID=<你的用户ID>
CLOUDFLARE_API_TOKEN=<你的令牌>
同时你可以在Actions secrets and variables的 Variables 中创建以下变量：

DB_NAME=<数据库名称，默认rin>
WORKER_NAME=<Cloudflare Worker 名称，默认rin-server>”

这里的“rin-server”是指文档前面提到的在Pages中创建的rin?还是指需要在Workers新创建rin-server的项目？

**Comment by OXeu** [comment]
Page 和 Worker 在 Cloudflare 中是独立的，rin-server 是 Worker 的默认名称，如果没有需求的话可以不添加该环境变量保持默认即可
