### ISSUE TITLE
[Feature Request] 对话框优化

### ISSUE THREAD

**Issue by OXeu** [OXeu/Rin#124]
**您的功能请求是否与问题相关？请描述**

当前对话框与提示框均使用浏览器默认提供的 alert 和 confirm，不够美观且体验割裂

**描述您想要的解决方案**

统一弹窗风格和 api

**描述你考虑过的替代方案**

**其他信息**

**Comment by SliverKeigo** [comment]
請問有正在考慮的UI組件庫嗎?

**Comment by OXeu** [comment]
> 請問有正在考慮的UI組件庫嗎?

目前使用的组件比较杂，暂时没有考虑用特定的组件库
