### ISSUE TITLE
[Help]能改网站的字体吗

### ISSUE THREAD

**Issue by exshin-stack** [OXeu/Rin#125]

**Comment by OXeu** [comment]
目前不能通过配置修改，但是可以自行修改以下字体相关的样式
https://github.com/OXeu/Rin/blob/5d31d7c84c781daa5fcc8f0aa6d96de8a049c712/client/index.html#L11-L14
https://github.com/OXeu/Rin/blob/5d31d7c84c781daa5fcc8f0aa6d96de8a049c712/client/src/index.css#L6-L21
