### ISSUE TITLE
[Help] 请问，如何验证后端是否搭建成功？或者说，如何添加文章？

### ISSUE THREAD

**Issue by SoMeTech** [OXeu/Rin#126]
按照部署手册，搭建了一下
目前的状态是，前端可以访问了，文章是空的，也不知道如何 添加文章

我的前端网址（pages，自定义域名）https://52uvw.xyz
我的后端网址：（workers，自定义域名）https://servers.52uvw.xyz

前后端的cloudflare域名（非定义域名）分别为：
前端：rin-56k.pages.dev
后端：rin-server.hwhtj.workers.dev

**Comment by OXeu** [comment]
直接访问后端出现默认的`Hi`说明基本的配置是已经完成了
看起来后端是已经配置好了，但是Pages的 API_URL 环境变量没有指向`https://servers.52uvw.xyz`，而是指向的 `https://rin-server.hwhtj.workers.dev`，这个网址我这边目前打开是 404 的状态
一切都完成以后点击 GitHub 登录后即可添加文章（只有第一个登录的用户才有权限）

**Comment by OXeu** [comment]
至于你的后端地址`https://servers.52uvw.xyz/`似乎是被你其他的服务给占用了，响应的结果永远是`你好，干嘛呢`

**Comment by SoMeTech** [comment]
访问后端地址显示：你好，干嘛呢 是因为我修改workers.js代码，没改其他，就是把hello world改成了“你好，干嘛呢”
点击前端右上角的 Github 登录，打开的网址是https://servers.52uvw.xyz/user/github，并没有出来添加文章的地方。是我在fork的仓库中修改的那些变量，未能部署到workers吗？

**Comment by OXeu** [comment]
看了你fork的仓库，没有触发过 Github Action 部署后端，请参照部署文档在仓库的设置中配置好环境变量以后激活 GitHub Action并手动触发一次

**Comment by SoMeTech** [comment]
就是部署手册中的这句话”完成准备工作以后即可在 GitHub Action 中手动触发一次 Workflow，“没有理解，不知道如何 操作。
我试过在setting-actions-General-Workflow permissions下面点击 ”save“,结果好像没用

**Comment by SoMeTech** [comment]
在网上搜索了如何触发workflow,好像要写脚本？https://blog.csdn.net/m0_57236802/article/details/133821883

**Comment by OXeu** [comment]
> 就是部署手册中的这句话”完成准备工作以后即可在 GitHub Action 中手动触发一次 Workflow，“没有理解，不知道如何 操作。
> 我试过在setting-actions-General-Workflow permissions下面点击 ”save“,结果好像没用

不在 Setting 中，点击顶部的 Actions 选项卡然后启用即可
