### ISSUE TITLE
[Help] "完成准备工作以后即可在 GitHub Action 中手动触发一次 Workflow"部署文档中的这句话要如何 操作吗？

### ISSUE THREAD

**Issue by SoMeTech** [OXeu/Rin#127]
我在自己fork的仓库中，应该如何操作，才能”在 GitHub Action 中手动触发一次 Workflow“

**Comment by OXeu** [comment]
![2024-06-07 23-49-36 mkv_20240615_195401 249](https://github.com/OXeu/Rin/assets/36541432/305e28fd-8065-4f24-814b-517946024c30)
![2024-06-07 23-49-36 mkv_20240615_195411 259](https://github.com/OXeu/Rin/assets/36541432/8dc1613f-0763-4cc5-9e57-d88ed5c47187)

**Comment by SoMeTech** [comment]
谢谢你耐心的指导
