### ISSUE TITLE
后端部署完访问无响应

### ISSUE THREAD

**Issue by LucaModric** [OXeu/Rin#130]
完全按视频操作的，在github加了5个配置：RIN_GITHUB_CLIENT_ID，RIN_GITHUB_CLIENT_SECRET，JWT_SECRET，CLOUDFLARE_ACCOUNT_ID，CLOUDFLARE_API_TOKEN，手动触发Workflow部署完成，访问后端地址，直接无响应（视频中是返回了一个hi 显示在页面）。

![五个配置不成功](https://github.com/OXeu/Rin/assets/27324489/6b9dbdf2-af39-42a2-9a21-fbe4d9924d2a)
![无响应](https://github.com/OXeu/Rin/assets/27324489/ecbdf301-3a10-4ea9-ac0d-0ff0b56e6861)

请问这个和缺少配置无关吧？视频中作者您也没加S3_BUCKET和S3_REGION这几个配置项，另外如果要加，那么 “然后在公开访问处绑定一个域名用于访问资源，绑定的域名对应于S3_ACCESS_HOST环境变量，S3_ACCESS_HOST=https://image.xeu.life” ，这个S3_ACCESS_HOST绑定的域名是需要自己购买的域名？

**Comment by OXeu** [comment]
workers.dev 应该是半墙状态，不配置自己的域名的话就需要特殊网络环境了
