### ISSUE TITLE
[Feature Request] 将头像作为网站图标

### ISSUE THREAD

**Issue by nashi23** [OXeu/Rin#131]
**您的功能请求是否与问题相关？请描述**

当前网站图标是通过 `client/public/favicon.png` 确定的。

**描述您想要的解决方案**

希望通过 https://wsrv.nl/ 将 `AVATAR` 处理为圆形，并且将圆形外的部分设为透明背景，作为网站图标。

**描述你考虑过的替代方案**

**其他信息**

**Comment by SliverKeigo** [comment]
也许可以考虑将网站图标url放到环境变量中
