### ISSUE TITLE
[Help] 问题描述登录后端是出现1101错误

### ISSUE THREAD

**Issue by maxweiwei** [OXeu/Rin#137]
**描述你遇到的问题**
本人小白,如果问题过于幼稚请谅解
**复现步骤**
1. 登录 https://blog.8072211.xyz/
2. 右上角点击登录后跳转https://rin.8072211.xyz/user/github
3. 然后就出现错误了折腾了好几遍也不行

**期望行为**

**截图**
<img width="646" alt="image" src="https://github.com/OXeu/Rin/assets/37798522/0ba37183-5922-4203-89ad-809b4b830ff5">

**额外信息**

**Comment by OXeu** [comment]
1101 说明存在关键环境变量没有配置，参考#42

**Comment by maxweiwei** [comment]
来信已收到。

**Comment by maxweiwei** [comment]
> 1101 说明存在关键环境变量没有配置，参考#42

添加了jmt变量后就成功了,谢谢
