### ISSUE TITLE
[Help] 您好，我跟随视频部署，最后一步登录出现问题

### ISSUE THREAD

**Issue by xitian666** [OXeu/Rin#140]
点击登录后出现NOT_FOUND
网址是https://rin-server.xxx.workers.dev//user/github

输入https://rin-server.xxx.workers.dev/user/github
后出现Referer not found

**Comment by PBK-B** [comment]
> @xitian666 啥视频呀？链接能分享一下吗

看到咧，部署教程里的呀

**Comment by xitian666** [comment]
> > @xitian666 啥视频呀？链接能分享一下吗
> 
> 看到咧，部署教程里的呀

是的，我跟随视频教程部署，没有成功，你成功了吗？

**Comment by HuIn2479** [comment]
将 "修改PagesAPI_URL" 那里填入的链接后面的 "/" 删了就行

<img width="458" alt="PixPin_2024-06-25_09-41-24" src="https://github.com/OXeu/Rin/assets/66163050/95286518-43fa-4f97-a429-e03ecdc94708">

**Comment by xitian666** [comment]
> 将 “修改 Pages API_URL” 那里填入的链接后面的 “/” 删了就行
> 
> <img alt="PixPin_2024-06-25_09-41-24" width="458" src="https://private-user-images.githubusercontent.com/66163050/342546352-95286518-43fa-4f97-a429-e03ecdc94708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDYwNDgsIm5iZiI6MTcxOTMwNTc0OCwicGF0aCI6Ii82NjE2MzA1MC8zNDI1NDYzNTItOTUyODY1MTgtNDNmYS00Zjk3LWE0MjktZTAzZWNkYzk0NzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4NTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMGM4M2U3ODg1M2ZlN2JiMGE2ZTgzZTg2YWU2MGMyNGMzMzZmMzJkNWJlYjcwNThhZjk1NTlmOGE0NWQzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FxfjcurbVzND5DIhHes-VSVXuG0LXWaC3UNWdRQUYaQ">

好的，谢谢
