### ISSUE TITLE
[Feature Request] 防盗刷设计

### ISSUE THREAD

**Issue by chesha1** [OXeu/Rin#147]
目前的图片还是都是来源一个可以从公网直接访问的图床，这样不太安全

既然用的是 cloudflare 全家桶，有没有考虑过在 pages 上加上 binding，只从内网访问 r2 上的资源

**Comment by OXeu** [comment]
如果直接使用 R2 的话，通常来讲 Cloudflare 的 CDN 是能缓存大部分请求的，应该能在一定程度上防止盗刷？

**Comment by chesha1** [comment]
万一我设置不用缓存，恶意地就是要把你的 r2 访问次数刷完，用 cdn 也没用吧？

最安全的做法还是设置图片的请求只能从你的网页上发起（这样还能顺便防止你的文章被盗），同时加上频控

**Comment by OXeu** [comment]
除了浏览器本地的缓存以外，CDN上也是有缓存的，CDN的缓存是不受请求参数的影响的

**Comment by OXeu** [comment]
> 最安全的做法还是设置图片的请求只能从你的网页上发起（这样还能顺便防止你的文章被盗），同时加上频控

不过确实应该考虑安全性的问题，我思考一下有什么比较好的解决方案没有

**Comment by chesha1** [comment]
我如果我没理解错的话，[`Cache-Control` 是会影响 CDN 的行为的](https://developers.cloudflare.com/cache/concepts/cache-control/)

请求参数确实不重要，[设置一下](https://developers.cloudflare.com/cache/how-to/set-caching-levels/)就能防止请求参数变更带来的攻击

**Comment by OXeu** [comment]
[Cache-Control](https://developers.cloudflare.com/cache/concepts/cache-control/) 是源服务器（这里是 R2）的响应头中的参数，不是请求参数

**Comment by chesha1** [comment]
我在 16:30 的时候，密集地请求了 100 次某个图片，麻烦到 r2 的 metrics 里看下，是否请求确实没有打到 r2 的文件上

**Comment by OXeu** [comment]
![图片](https://github.com/OXeu/Rin/assets/36541432/e7680c55-41e8-4b38-87fe-2d2eb1695637)
16:30 前后的 B 类请求次数维持在较低水平，最高点位于 16:18 分有 33 次

**Comment by chesha1** [comment]
那应该是没打到 r2 上，感谢你提供的结果，如果将来有好的防盗刷设计，或者在 rin 里已经完成完整的防盗刷实现了，麻烦@我一下
