### ISSUE TITLE
[Bug] 更新文章之后 feed 缓存不会刷新

### ISSUE THREAD

**Issue by liuran001** [OXeu/Rin#153]
**Bug 描述**
如题，当我新建或更改一篇文章之后，可以直接访问这篇文章，而且时间线中能够正常显示
但主页不会显示这篇文章

**复现步骤**
我新建了一篇名为 test 的文章，在时间线可以看到
![image](https://github.com/OXeu/Rin/assets/32791471/76a0adb7-2f64-4f28-9578-e1cabe29b92b)
但主页并没有显示
![image](https://github.com/OXeu/Rin/assets/32791471/14ff4ff8-ee17-4514-b029-64c0d88885a1)
直接请求 `/feed?page=1&limit=6&type=normal` 不显示最新文章
![image](https://github.com/OXeu/Rin/assets/32791471/fb2d2e64-2a2c-4155-9fbf-c0498bc2e540)
修改参数使其不命中缓存后正常显示
![image](https://github.com/OXeu/Rin/assets/32791471/2967104f-c376-4786-8c90-2deb31798e14)

**期望行为**
在修改文章后强制重新刷新或移除缓存

**Comment by OXeu** [comment]
请尝试合并 dev 分支的更改后在设置中`清空缓存`，之后再测试缓存是否正常工作

**Comment by liuran001** [comment]
@OXeu 合并了最新 main 分支（看到的时候 dev 已经合到 main 了）清空缓存后显示正常，但现在无法正常编辑和新建文章
点击发布后控制台报错
已尝试关闭 Cloudflare Rocket Loader 并更换浏览器，问题依旧

![image](https://github.com/OXeu/Rin/assets/32791471/7aa339e6-62ca-4902-959b-f25fe725e03d)

**Comment by OXeu** [comment]
抱歉这是引入 i18n 导致的错误，现在已经修复了
