### ISSUE TITLE
[Feature Request] 新的MD渲染器与站点主题不太匹配，且缺失一些原有功能

### ISSUE THREAD

**Issue by ElluIFX** [OXeu/Rin#157]
**您的功能请求是否与问题相关？请描述**
- 代码高亮强调色与之前不同了，不再匹配Rin主题色
- [x] 二级标题现在多了个默认的分划线，有点突兀，且容易造成一、三级标题的混淆
- [x] 一键代码复制的功能消失了
- [x] Github MD渲染器风格的特殊标记不再生效（如`[!NOTE]`）
- 未发现的其他差异

**描述您想要的解决方案**
- 优化新渲染器的默认主题文件（或许有？）
- 看看能不能把缺失的功能通过插件之类的加回来

**描述你考虑过的替代方案**
- 提供对旧渲染器的全局fallback选项，更激进的话，尝试允许针对文章选择不同的渲染器

**Comment by ElluIFX** [comment]
修改来自 #143

**Comment by OXeu** [comment]
新的渲染组件目前确实破坏了很多功能和样式，我最近会尝试修复或者重写这部分的代码

**Comment by OXeu** [comment]
代码高亮强调色目前暂不调整

**Comment by ElluIFX** [comment]
> 代码高亮强调色目前暂不调整，其他任务已完成

非常Nice
