### ISSUE TITLE
[Bug] 目录显示异常

### ISSUE THREAD

**Issue by liuran001** [OXeu/Rin#165]
**Bug 描述**

文章内目录显示异常，当前页面与显示目录不符，且点击目录无法跳转到对应位置
而且目录显示也不完整，比如图中用的是 `### 配置 Cloudflare R2 存储桶`，目录却没有显示
![image](https://github.com/OXeu/Rin/assets/32791471/59905b0d-0dda-4d83-acdf-cfc1bb601d2a)
而这里的 `### 它适合哪些人` 却显示在目录上了
![image](https://github.com/OXeu/Rin/assets/32791471/e6e8b8bb-e387-45de-b18b-c2bf1d6cb251)
（例子 https://blog.obdo.cc/feed/10 ）

**期望行为**

指示当前位置对应目录，点击目录可跳转到文章对应位置

**Comment by OXeu** [comment]
这是更换新的渲染组件之后的已知问题，晚点修复
