### ISSUE TITLE
[Help] 问题 描述登录功能为什么用不了呢 

### ISSUE THREAD

**Issue by TIANXUAN13** [OXeu/Rin#166]
**描述你遇到的问题**
无法使用github登录
点击右上角github登录跳转的页面是 https:// rin-server.gcst4tqsdm.workers.dev//user/github 显示的是NOT_FOUND

**期望行为**

**截图**
![image](https://github.com/OXeu/Rin/assets/92909805/6484e192-9b1e-43ee-af85-796769c10637)

构建都是正常的，环境变量都添加了

**Comment by TIANXUAN13** [comment]
现在能够使用登录了，参考了#63 但是登录后显示的NOT_FOUND 链接是入下
https://[rin-server.gcst4tqsdm.workers.dev/callback?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.fL_hQDn1SNxEVcwL6mNJwMUYl7OFPh1OYCzmc-rzStg](https://rin-server.gcst4tqsdm.workers.dev/callback?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MX0.fL_hQDn1SNxEVcwL6mNJwMUYl7OFPh1OYCzmc-rzStg)
截图如下
![image](https://github.com/OXeu/Rin/assets/92909805/890f93cc-b6ea-4ef2-8730-0330b2999d17)

**Comment by OXeu** [comment]
请检查 GitHub OAuth 回调地址
参考：https://github.com/OXeu/Rin/issues/63#issuecomment-2155792790

**Comment by TIANXUAN13** [comment]
回调地址我填写的是
https://rin-server.gcst4tqsdm.workers.dev/user/github/callback
在actions中的构建中复制的，访问显示的是hi

**Comment by OXeu** [comment]
方便贴一下前端地址吗

**Comment by TIANXUAN13** [comment]
前端地址https://rin-7ji.pages.dev/

**Comment by TIANXUAN13** [comment]
诶，我为什么不行呀，我再试试看，谢谢你啦

**Comment by OXeu** [comment]
> 诶，我为什么不行呀，我再试试看，谢谢你啦

请直接尝试从前端登录，直接打开后端的地址不行

**Comment by TIANXUAN13** [comment]
佬，我真的绷不住了，我手机都可以用前端登上去，但是我使用edge电脑浏览器就是登录不上，还是会返回NOT_FOUND
这个真的有点离谱啦

**Comment by OXeu** [comment]
> 佬，我真的绷不住了，我手机都可以用前端登上去，但是我使用edge电脑浏览器就是登录不上，还是会返回NOT_FOUND
> 这个真的有点离谱啦

暂时没有想到为什么会有这个问题，你用Edge开隐私标签页再访问试试？

**Comment by TIANXUAN13** [comment]
现在刚刚登录上，我把拦截广告的adguard关闭了，然后多试了几次就可以访问了，感谢回复

**Comment by TIANXUAN13** [comment]
佬，想再问问这个项目部署之后写了内容，在cloudflare后端再次重新部署会不会把之前写的数据丢失

**Comment by OXeu** [comment]
> 佬，想再问问这个项目部署之后写了内容，在cloudflare后端再次重新部署会不会把之前写的数据丢失

不会

**Comment by TIANXUAN13** [comment]
好的，感谢您，现在我想用国内的CDN加速后端服务器的域名可以不，我这主要是后端访问不到，前端倒是跑挺快，有没有反馈是通过加速后端域名的教程呀

**Comment by OXeu** [comment]
> 好的，感谢您，现在我想用国内的CDN加速后端服务器的域名可以不，我这主要是后端访问不到，前端倒是跑挺快，有没有反馈是通过加速后端域名的教程呀

后端默认域名是半墙状态，绑定一个自定义的域名通常就能解决问题

**Comment by TIANXUAN13** [comment]
好滴，谢谢，我尝试一下

**Comment by TIANXUAN13** [comment]
非常感谢大佬，经过后端绑定域名，现在访问速度确实不需要开梯子就可以使用了，感谢感谢

**Comment by soslane** [comment]
> > 好的，感谢您，现在我想用国内的CDN加速后端服务器的域名可以不，我这主要是后端访问不到，前端倒是跑挺快，有没有反馈是通过加速后端域名的教程呀
> 
> 后端默认域名是半墙状态，绑定一个自定义的域名通常就能解决问题

后端怎么绑定域名啊

**Comment by TIANXUAN13** [comment]
> > > 好的，感谢您，现在我想用国内的CDN加速后端服务器的域名可以不，我这主要是后端访问不到，前端倒是跑挺快，有没有反馈是通过加速后端域名的教程呀
> > 
> > 
> > 后端默认域名是半墙状态，绑定一个自定义的域名通常就能解决问题
> 
> 后端怎么绑定域名啊

绑定域名就在cloudflare里面 进入后端的设置里面，里面绑定自定义域名，就可以了，访问速度明显加快

**Comment by TIANXUAN13** [comment]
> > > 好的，感谢您，现在我想用国内的CDN加速后端服务器的域名可以不，我这主要是后端访问不到，前端倒是跑挺快，有没有反馈是通过加速后端域名的教程呀
> > 
> > 
> > 后端默认域名是半墙状态，绑定一个自定义的域名通常就能解决问题
> 
> 后端怎么绑定域名啊

![image](https://github.com/OXeu/Rin/assets/92909805/432b4710-d01e-40e1-8218-984582a160e2)

**Comment by soslane** [comment]
github里面要改吗？就是homepage URL和Authorization callback URL需要改吗

**Comment by TIANXUAN13** [comment]
> github里面要改吗？就是homepage URL和Authorization callback URL需要改吗

应该要改的，你改了然后在cloudflare重新部署下试试访问怎么样，我现在是homepage URL没改
Authorization callback URL这个改成我的自定义域名，那个域名加后面的不变的那一串路径

**Comment by soslane** [comment]
哦，谢谢，我一会去试试

**Comment by soslane** [comment]
试了，还是不行，国内网络无法刷出文章.开代理可以

**Comment by TIANXUAN13** [comment]
晚点我再跟你说吧，现在有事，可以加个联系方式

**Comment by soslane** [comment]
搞好了，环境变量的URL也要改一下，谢谢。摸出来了！
