### ISSUE TITLE
markdown编辑表格时光标不在表格内

### ISSUE THREAD

**Issue by onshine** [OXeu/Rin#170]
**Bug 描述**
1.markdown编辑表格时光标不在表格内，第三行的Cell无法编辑
2.点击文章，显示首页文章列表时，所有文章会连续闪（可能是快速刷新）3次；

**复现步骤**
1.
1）. 前往 写作
2）. 点击 表格，
3）. 出现 header和cell

2.随便点“时间轴”/“写作”/“朋友们”/“关于”，再点击文章，下面的文章列表就会连续闪（可能是快速刷新）3次；

**期望行为**
1.
markdown表格可以正常显示编辑，

2.
点击文章，正常显示加载即可

**截图**
1.
![image](https://github.com/OXeu/Rin/assets/95197697/d6a954f5-065a-4f18-adcc-ea13bc8adb26)

2.
![image](https://github.com/OXeu/Rin/assets/95197697/15cdd8a4-2fa4-4c23-87a4-ca4c3b2fbeae)

**环境变量**
无

**Comment by OXeu** [comment]
文章连续闪烁目前没有成功复现
