### ISSUE TITLE
[Help] 无法登录

### ISSUE THREAD

**Issue by jelee2024** [OXeu/Rin#171]
**早在六月十多号，就发现该项目并且部署，但无论是6月十多号，根据文档的部署，
还是最近根据视频一步步的部署，都会有一个问题，无法登录。404: No such page!
无论是反复删除重建，还是各种各样的方法，换过github账号，cf账号，什么都试过了，一样的问题，很困惑。
**复现步骤**
1. 无论使用电脑浏览器还是手机浏览器都无法打开登录，提示{404: No such page!}
2. xxx

**期望行为**
成功登入

**截图**
![image](https://github.com/OXeu/Rin/assets/172282951/3565eebb-a8ec-41ce-b965-7f03846cf59d)

**额外信息**
部署：https://rin-98s.pages.dev
我反复确认了后端地址：
https://rin-server.xh.workers.dev/user/github/callback

**Comment by jelee2024** [comment]
一切正常，就是无法登入
各种方法都尝试了，反复删除重建，换过github账号，cf账号。还是一样的问题
很困惑(•_•)?

**Comment by OXeu** [comment]
检查 Pages 环境变量 API_URL 是否为https://rin-server.xh.workers.dev

同时在修改环境变量后需要手动重新部署一次 Pages

**Comment by PBK-B** [comment]
@OXeu 你看这么多 issue 都是因为 github 的 OAuth 导致的，所以你快做账号密码登录功能

**Comment by jelee2024** [comment]
> 检查 Pages 环境变量 API_URL 是否为https://rin-server.xh.workers.dev
> 
> 同时在修改环境变量后需要手动重新部署一次 Pages

非常非常非常感谢
看到你的回复时，察觉到我可能是犯蠢了
