### ISSUE TITLE
[Feature Request] 希望改回之前左右对照的markdown编辑模式

### ISSUE THREAD

**Issue by sergioperezcheco** [OXeu/Rin#175]
**您的功能请求是否与问题相关？请描述**

现在的写作模块中取消了顶部的工具栏，功能比之前少了很多。现在取消了左右对照，预览需要点来点去也很麻烦。而且现在不能直接粘贴图片，只能去图床生成url在生成，或者保存到本地再上传。在写博客的时候截完图不能直接粘贴有点影响体验。
![12c274648ad6bdb37dc2c.png](https://img.checo.cc/file/12c274648ad6bdb37dc2c.png)

**描述您想要的解决方案**

希望能恢复成之前左右对照的编辑模式，类似下图这种。
![2abe2f0333144ae46f064.png](https://img.checo.cc/file/2abe2f0333144ae46f064.png)

**描述你考虑过的替代方案**

或许可以加上切换按钮，切换两种编辑模式以保住左右对照，但是拜托大佬保留编辑栏以及直接粘贴图片的功能，这能为我们写作提供方便。

**其他信息**

期待大佬的更新

**Comment by OXeu** [comment]
左右对照在文本量比较大的时候页面性能会很差，后续会加上，不过不会是默认状态

**Comment by sergioperezcheco** [comment]
> 左右对照在文本量比较大的时候页面性能会很差，后续会加上，不过不会是默认状态

直接在输入框里粘贴图片呢，也是之前有但现在没有的功能

**Comment by OXeu** [comment]
> > 左右对照在文本量比较大的时候页面性能会很差，后续会加上，不过不会是默认状态
> 
> 直接在输入框里粘贴图片呢，也是之前有但现在没有的功能

这个是因为新的编辑器这块功能支持不太全，不过可以拖动上传，粘贴上传我后续再研究一下
