### ISSUE TITLE
[Bug] 别名页无法评论

### ISSUE THREAD

**Issue by SaintWe** [OXeu/Rin#179]
**Bug 描述**

 **复现步骤**

https://github.com/OXeu/Rin/blob/5a94a2c3ce7e0559b58cba195e2d7f0d0ea2263d/client/src/page/feed.tsx#L220

当从别名访问文章时，此处 id 会导致无法取得当前文章的评论列表以及提交评论

https://github.com/OXeu/Rin/blob/5a94a2c3ce7e0559b58cba195e2d7f0d0ea2263d/client/src/App.tsx#L105

**期望行为**

``` typescript
{feed && <Comments id={feed.id} />} 
```

**截图**

**环境变量**

**Comment by OXeu** [comment]
欢迎pr
