### ISSUE TITLE
[Feature Request] 全站加密

### ISSUE THREAD

**Issue by lemnrt** [OXeu/Rin#184]
**您的功能请求是否与问题相关？请描述**

希望增加全站加密

**描述您想要的解决方案**

设置密码后，全站前台所有页面访问需要输入密码

**描述你考虑过的替代方案**

**其他信息**

**Comment by OXeu** [comment]
这是什么特殊的需求吗？本项目初衷便是作为一个博客项目，对于特殊内容可以设置仅自己可见或不列出在列表中，基本能够满足大部分需求，至于全站加密目前没有想到对应的需求
