### ISSUE TITLE
[Bug] 设置中网站图标设置默认值不正确

### ISSUE THREAD

**Issue by SliverKeigo** [OXeu/Rin#198]
![image](https://github.com/OXeu/Rin/assets/112426853/40cf2442-ab3c-4367-bae9-4443fadb92e1)
在未修改情况下期望默认值为头像的url地址

**Comment by OXeu** [comment]
参见 #131
默认值为使用 wsnl 服务将头像处理为 favicon 合适的大小并裁切为圆形的链接，原始的头像不适合直接用做 favicon
不过由于忘记进行 URL 编码一些头像链接可能会无法生效，后面我修复一下

**Comment by SliverKeigo** [comment]
> 参见 #131 默认值为使用 wsrv 服务将头像处理为 favicon 合适的大小并裁切为圆形的链接，原始的头像不适合直接用做 favicon 不过由于忘记进行 URL 编码一些头像链接可能会无法生效，后面我修复一下

![recording](https://github.com/OXeu/Rin/assets/112426853/fd564027-f476-4e4b-8208-e5a75982ef3b)
 设置后没有生效
 
 
![recording](https://github.com/OXeu/Rin/assets/112426853/d16bcd6a-4965-4881-afc1-ac41d4a65185)
只输入图片url地址才生效

**Comment by OXeu** [comment]
> > 参见 #131 默认值为使用 wsrv 服务将头像处理为 favicon 合适的大小并裁切为圆形的链接，原始的头像不适合直接用做 favicon 不过由于忘记进行 URL 编码一些头像链接可能会无法生效，后面我修复一下
> 
> ![recording](https://github.com/OXeu/Rin/assets/112426853/fd564027-f476-4e4b-8208-e5a75982ef3b)
>  设置后没有生效
>  
>  
> ![recording](https://github.com/OXeu/Rin/assets/112426853/d16bcd6a-4965-4881-afc1-ac41d4a65185)
> 只输入图片url地址才生效
> 

不生效是正常的，我忘记对头像地址进行 URL 编码了

**Comment by SliverKeigo** [comment]
> > > 参见 #131 默认值为使用 wsrv 服务将头像处理为 favicon 合适的大小并裁切为圆形的链接，原始的头像不适合直接用做 favicon 不过由于忘记进行 URL 编码一些头像链接可能会无法生效，后面我修复一下
> > 
> > 
> > ![recording](https://private-user-images.githubusercontent.com/112426853/346432364-fd564027-f476-4e4b-8208-e5a75982ef3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyMzY0LWZkNTY0MDI3LWY0NzYtNGU0Yi04MjA4LWU1YTc1OTgyZWYzYi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDNjNTRiOWI0NWM2OGE5MTkwNmU5Y2IxODc5NTQ1YWEzZWY2MjUxZjA4YjhmM2QwMGY0NzkxYTBmNmE2OTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kHxnvQZuxlbW677Vm08SpW2V1FQxzfOjqEf_0DXthSc)
> >       
> >         [
> >           
> >         
> >             ![recording](https://private-user-images.githubusercontent.com/112426853/346432364-fd564027-f476-4e4b-8208-e5a75982ef3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyMzY0LWZkNTY0MDI3LWY0NzYtNGU0Yi04MjA4LWU1YTc1OTgyZWYzYi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDNjNTRiOWI0NWM2OGE5MTkwNmU5Y2IxODc5NTQ1YWEzZWY2MjUxZjA4YjhmM2QwMGY0NzkxYTBmNmE2OTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kHxnvQZuxlbW677Vm08SpW2V1FQxzfOjqEf_0DXthSc)
> >           ](https://private-user-images.githubusercontent.com/112426853/346432364-fd564027-f476-4e4b-8208-e5a75982ef3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyMzY0LWZkNTY0MDI3LWY0NzYtNGU0Yi04MjA4LWU1YTc1OTgyZWYzYi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDNjNTRiOWI0NWM2OGE5MTkwNmU5Y2IxODc5NTQ1YWEzZWY2MjUxZjA4YjhmM2QwMGY0NzkxYTBmNmE2OTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kHxnvQZuxlbW677Vm08SpW2V1FQxzfOjqEf_0DXthSc)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/112426853/346432364-fd564027-f476-4e4b-8208-e5a75982ef3b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyMzY0LWZkNTY0MDI3LWY0NzYtNGU0Yi04MjA4LWU1YTc1OTgyZWYzYi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDNjNTRiOWI0NWM2OGE5MTkwNmU5Y2IxODc5NTQ1YWEzZWY2MjUxZjA4YjhmM2QwMGY0NzkxYTBmNmE2OTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kHxnvQZuxlbW677Vm08SpW2V1FQxzfOjqEf_0DXthSc)
> >         
> >       
> > 设置后没有生效
> > ![recording](https://private-user-images.githubusercontent.com/112426853/346432554-d16bcd6a-4965-4881-afc1-ac41d4a65185.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyNTU0LWQxNmJjZDZhLTQ5NjUtNDg4MS1hZmMxLWFjNDFkNGE2NTE4NS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDRkNjYwZTY3NTAzNWY3ZjI2MGU3MmM4ZDc4ZDE3MTUyZmY1OWY3NzJmNzFlNDM0YTA4ZGQ0Nzk3ZWI0ZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P961qRmecdgGMzZYhLQf1ziz_sfBccH2RdliZFynWqA)
> >       
> >         [
> >           
> >         
> >             ![recording](https://private-user-images.githubusercontent.com/112426853/346432554-d16bcd6a-4965-4881-afc1-ac41d4a65185.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyNTU0LWQxNmJjZDZhLTQ5NjUtNDg4MS1hZmMxLWFjNDFkNGE2NTE4NS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDRkNjYwZTY3NTAzNWY3ZjI2MGU3MmM4ZDc4ZDE3MTUyZmY1OWY3NzJmNzFlNDM0YTA4ZGQ0Nzk3ZWI0ZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P961qRmecdgGMzZYhLQf1ziz_sfBccH2RdliZFynWqA)
> >           ](https://private-user-images.githubusercontent.com/112426853/346432554-d16bcd6a-4965-4881-afc1-ac41d4a65185.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyNTU0LWQxNmJjZDZhLTQ5NjUtNDg4MS1hZmMxLWFjNDFkNGE2NTE4NS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDRkNjYwZTY3NTAzNWY3ZjI2MGU3MmM4ZDc4ZDE3MTUyZmY1OWY3NzJmNzFlNDM0YTA4ZGQ0Nzk3ZWI0ZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P961qRmecdgGMzZYhLQf1ziz_sfBccH2RdliZFynWqA)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/112426853/346432554-d16bcd6a-4965-4881-afc1-ac41d4a65185.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjUzMTgsIm5iZiI6MTcyMDQyNTAxOCwicGF0aCI6Ii8xMTI0MjY4NTMvMzQ2NDMyNTU0LWQxNmJjZDZhLTQ5NjUtNDg4MS1hZmMxLWFjNDFkNGE2NTE4NS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNzUwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDRkNjYwZTY3NTAzNWY3ZjI2MGU3MmM4ZDc4ZDE3MTUyZmY1OWY3NzJmNzFlNDM0YTA4ZGQ0Nzk3ZWI0ZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P961qRmecdgGMzZYhLQf1ziz_sfBccH2RdliZFynWqA)
> >         
> >       
> > 只输入图片url地址才生效
> 
> 不生效是正常的，我忘记对头像地址进行 URL 编码了，头像地址中包含 ? & 都会不生效

![recording](https://github.com/OXeu/Rin/assets/112426853/a66eec4e-ddbf-4eef-84fd-9813fe8cedbb)
