### ISSUE TITLE
[Bug] 切换语言后目录无法显示

### ISSUE THREAD

**Issue by SliverKeigo** [OXeu/Rin#204]
**Bug 描述**

**复现步骤**

进入一篇文章后<https://rin.sliverkeigo.top/feed/7> 点击右上角修改语言 然后刷新页面 目录无法显示

**截图**
![20240708230730](https://github.com/OXeu/Rin/assets/112426853/5d5077f7-771f-4ce1-9a88-91888474ef1a)

**Comment by OXeu** [comment]
commit 5ed8ceb2014d74b91583c6bce6925dbf99f8039f 已修复，请重新同步最新 main 分支
