### ISSUE TITLE
[Bug]  提示不让添加以GITHUB开头的变量

### ISSUE THREAD

**Issue by sundys** [OXeu/Rin#36]
添加这两个变量，提示不让添加以GITHUB开头的变量，只能到cf上添加吗

GITHUB_CLIENT_ID=<你的GithubClientID>
GITHUB_CLIENT_SECRET=<你的GithubClientSecret>

**Comment by OXeu** [comment]
啊忘了这个问题了，这个确实不能添加，之前是在 Cloudflare 上配置的没有这个问题，暂时先在 Cloudflare 添加吧，后续改一下变量名
