### ISSUE TITLE
添加GITHUB_CLIENT_ID 出现问题

### ISSUE THREAD

**Issue by JohnMing143** [OXeu/Rin#40]
**描述你遇到的问题**
在按照添加 CLOUDFLARE_ACCOUNT_ID 与 CLOUDFLARE_API_TOKEN步骤添加GITHUB_CLIENT_ID时被提示secrets不能以 GITHUB_ 开头
**复现步骤**
1. 在fork 的仓库中 > Settings > Secrets and Variables > Actions > Repository secrets 点击 New repository secret 创建添加GITHUB_CLIENT_ID
2. 提示secrets不能以 GITHUB_ 开头

**期望行为**
获得正确指引

**截图**

![Snipaste_2024-06-07_17-38-37](https://github.com/OXeu/Rin/assets/126879422/7e044ece-2a79-4277-acff-a8bef83fed74)

**Comment by OXeu** [comment]
仓库同步一下最新分支，将`GITHUB_CLIENT_ID`添加`RIN_`前缀，即修改为`RIN_GITHUB_CLIENT_ID`，secret同理，具体请参见<https://github.com/OXeu/Rin/blob/main/docs/DEPLOY.md#v020-2024-06-07-更新>
