### ISSUE TITLE
[Help] 部署后端，按教程添加完所有key和变量，但是访问后端500

### ISSUE THREAD

**Issue by sundys** [OXeu/Rin#42]
后端的变量，全部添加了，检查了几遍还是这样，

前端点github登陆就提示无法处理此请求。HTTP ERROR 500，好像无法https加密访问呢。

github也创建了应用返回地址，KEY也加到了后端变量，不知道哪里出问题了。

**Comment by OXeu** [comment]
方便贴一下以下内容吗？

* github oauth 的配置
* Cloudflare Workers 的环境变量 cloudfare 控制面板可查看（如果是明文的话注意隐藏密钥）
* Cloudflare Pages可以直接访问的地址

**Comment by OXeu** [comment]
看了下你的 CI，除此以外还需要配置以下环境变量
参考最新的部署文档的 [配置 Github Action](https://github.com/OXeu/Rin/blob/main/docs/DEPLOY.md#%E9%85%8D%E7%BD%AE-github-action) 模块
```ini
RIN_GITHUB_CLIENT_ID=<你的GithubClientID>
RIN_GITHUB_CLIENT_SECRET=<你的GithubClientSecret>
JWT_SECRET=<JWT 认证所需密钥，可为常规格式的任意密码>
S3_ACCESS_KEY_ID=<你的S3AccessKeyID>
S3_SECRET_ACCESS_KEY=<你的S3SecretAccessKey>
```
其中考虑到你可能已经在 Cloudflare 面板配置了 `GITHUB_CLIENT_ID` 和 `GITHUB_CLIENT_SECRET` （有无 `RIN_` 前缀等效），你还至少需要配置 `JWT_SECRET` 才能正常启动后端，至于另外两个 S3 的变量并非启动后端必须

`JWT_SECRET` 用于后端与前端安全的交换加密的用户凭据，其值可以是任意格式的密码，如：
```ini
JWT_SECRET=Ju$tChanGE@Meeeee
```
