### ISSUE TITLE
[Bug]D1_ERROR: NOT NULL constraint failed: users.username

### ISSUE THREAD

**Issue by lekai63** [OXeu/Rin#43]
**Bug 描述**
部署后，前端已正常显示。点击“github登陆”，转入后端api地址时，网页出现
D1_ERROR: NOT NULL constraint failed: users.username

cf端日志流 都显示“ok”

**期望行为**
正常登陆

**截图**

**环境变量**

**Comment by lekai63** [comment]
看了下源码。手工到D1数据库里加了下username啥的，好像还不行

**Comment by OXeu** [comment]
可能是GitHub 账户隐私权限的问题，可以尝试重新登录试一下

**Comment by OXeu** [comment]
> 可能是GitHub 账户隐私权限的问题，可以尝试重新登录试一下

我在你部署的站点尝试了下可以正常登录

**Comment by lekai63** [comment]
> 明白了，Github OAuth 获取用户资料时使用了 name 字段，但是你的 Github 账户只设置了用户名，并没有设置名称导致获取到的值为 null，晚点我更新一个补丁修一下

嗯啊。我也是刚发现了这个问题 囧。更新了下自己的profile后 好了。
