### ISSUE TITLE
[Help] 问题描述

### ISSUE THREAD

**Issue by ossssss6** [OXeu/Rin#46]
**描述你遇到的问题**
Github Actions里run workflow的Deploy时会提示Failed to create D1 "rin"
**复现步骤**
1. run workflow的Deploy时

**期望行为**
成功创建D1 rin

**截图**
![image](https://github.com/OXeu/Rin/assets/93513538/558d04e9-87d4-4334-bdd8-4301b41b3fef)

**额外信息**
我在cloudflare里创不创建rin都会报错

**Comment by OXeu** [comment]
我新提交了一个补丁尝试输出更多创建失败时错误信息，你可以先同步一下仓库再重新尝试一下看一下新的错误输出。

同时请检查一下 `CLOUDFLARE_ACCOUNT_ID` 与 `CLOUDFLARE_API_TOKEN` 是否填写有误，包括但不限于：
* ID 与 Secret 填写反了
* 区域 ID 被误当作用户 ID 复制
* 变量名与值中存在空格
* 误删或多追加了字符

**Comment by OXeu** [comment]
看到最新的报错信息了，如果在 `CLOUDFLARE_ACCOUNT_ID` 与  `CLOUDFLARE_API_TOKEN` 都设置无误的前提下请检查你的 API TOKEN 是否授予了 D1 的编辑权限
![图片](https://github.com/OXeu/Rin/assets/36541432/9982de85-3d33-4c2c-af1c-0a935b17fd29)

**Comment by ossssss6** [comment]
看来是权限的问题，谢谢大佬！
