### ISSUE TITLE
[Feature Request] Full support for hashtags

### ISSUE THREAD

**Issue by OXeu** [OXeu/Rin#50]
**Is your feature request related to the problem? Please describe**

Currently, tag support is very rudimentary and only supports display, not querying by tag or viewing tag lists

**Describe the solution you want**

* [x] Add a tag list page
* [x] Add support for clicking on a tag to query related articles
* [ ] Automatically remove duplicate tags
* [ ] Regularly remove unreferenced tags

**Comment by PBK-B** [comment]
cool
