### ISSUE TITLE
手动触发一次 Workflow提示没有CLOUDFLARE_API_TOKEN

### ISSUE THREAD

**Issue by lqdahv** [OXeu/Rin#56]
**描述你遇到的问题**

**复现步骤**
1. xxxxx
2. xxx

**期望行为**

**截图**

![QQ截图20240608022307](https://github.com/OXeu/Rin/assets/24808833/d2cd0a56-366b-467c-b603-e7ae139306e3)

**额外信息**
![QQ截图20240608022054](https://github.com/OXeu/Rin/assets/24808833/49eb0055-b7ef-4a8d-9633-f53e24092f1e)

**Comment by OXeu** [comment]
Secret是逐条添加，不是直接粘贴AAA=BBB
示例：
名称：AAA（图中RIN的位置）
值：BBB（图中大编辑框中的值）
