### ISSUE TITLE
[Feature Request] 希望可以支持导入 WordPress 导出的文件

### ISSUE THREAD

**Issue by chentao1006** [OXeu/Rin#57]
希望可以支持批量导入数据，方便迁移博客。
附件是从Wordpress导出的XML文件，包括了分类、标签、文章、评论等数据。
非常感谢！

[chentao1006.wordpress.com-2024-06-08-01_00_51-9ajuquistbf8tch7qpclkec2asruqaus.zip](https://github.com/user-attachments/files/15746002/chentao1006.wordpress.com-2024-06-08-01_00_51-9ajuquistbf8tch7qpclkec2asruqaus.zip)

**Comment by OXeu** [comment]
已支持
![图片](https://github.com/OXeu/Rin/assets/36541432/8dbde59e-97e1-4d13-b7eb-dcc844750813)
![图片](https://github.com/OXeu/Rin/assets/36541432/5c822839-3110-4727-a092-e5d6bb759869)

**Comment by OXeu** [comment]
目前已支持迁移的内容有：
* 文章标题正文与发布修改时间
* Category 按照标签导入
* 自动去除重复导入的内容

目前暂不支持的内容有：
* 分类
* 评论

**Comment by chentao1006** [comment]
辛苦啦！非常感谢

**Comment by SoMeTech** [comment]
> 辛苦啦！非常感谢



> 目前已支持迁移的内容有：
> 
> * 文章标题正文与发布修改时间
> * Category 按照标签导入
> * 自动去除重复导入的内容
> 
> 目前暂不支持导入的内容有：
> 
> * 分类
> * 评论
> 
> 计划在未来支持分类与免登录评论后可直接增量导入当前未支持的内容

请问，如何导入wordpress导出的 文件，是否需要借助第三方软件？

**Comment by OXeu** [comment]
> > 辛苦啦！非常感谢
> 
> > 目前已支持迁移的内容有：
> > 
> > * 文章标题正文与发布修改时间
> > * Category 按照标签导入
> > * 自动去除重复导入的内容
> > 
> > 目前暂不支持导入的内容有：
> > 
> > * 分类
> > * 评论
> > 
> > 计划在未来支持分类与免登录评论后可直接增量导入当前未支持的内容
> 
> 请问，如何导入wordpress导出的 文件，是否需要借助第三方软件？

WordPress 导出的文件通常为 zip 压缩包格式，将压缩包解压能够得到一个 xml 文件

同步仓库到最新分支，在`设置`页面有导入按钮，点击导入选择解压得到的 xml 上传即可

![图片](https://github.com/OXeu/Rin/assets/36541432/841a1e91-bed5-4c50-a701-603bff7d7d84)
