### ISSUE TITLE
[Help] 404: No such page!

### ISSUE THREAD

**Issue by ossplus** [OXeu/Rin#63]
**描述你遇到的问题**

**复现步骤**
依教程部署完毕，
1. 前端已部署
2. 后端也已部署（cf上已生成worker和d1数据库）
3. 已创建github的oauth app
4. 访问网址，点 GIthub登陆，会 跳转到domian/user/github  显示 404: No such page!

**期望行为**

**截图**

**额外信息**

**Comment by WTNLXTBL** [comment]
看样子应该是你的 Github OAuth Apps 中的 'Authorization callback URL' 填错了
需要改为'https://<你的后端地址>/user/github/callback'

**Comment by martin90s** [comment]
same issue. my setting: https://rin-server.martin-junhong.workers.dev/user/github/callback 看上去也不work

**Comment by gty198** [comment]
> 看样子应该是你的 `Github OAuth Apps` 中的 `Authorization callback URL` 填错了 需要改为 `https://<你的后端地址>/user/github/callback`

修改好之后要重新部署吗，还是会自动生效？

**Comment by gty198** [comment]
原来worker是执行完教程内容之后自动在cloudflare后台生产的，跟前段page名字一样
后续在API_URL填写正确之后在page那里重试部署
