### ISSUE TITLE
[Feature Request] 输出xml

### ISSUE THREAD

**Issue by ossplus** [OXeu/Rin#75]
**您的功能请求是否与问题相关？请描述**

RSS方式，方便聚合

**描述您想要的解决方案**
- RSS
- Atom
- JSON Feed
- 
**描述你考虑过的替代方案**

**其他信息**

**Comment by OXeu** [comment]
已加入 v0.3.0 计划，同时欢迎 PR

**Comment by OXeu** [comment]
已支持，参见文档：[RSS 支持与配置](https://github.com/OXeu/Rin/blob/main/docs/RSS.md)
