### ISSUE TITLE
[Feature Request] Worker 迁移到 Pages Function

### ISSUE THREAD

**Issue by SaintWe** [OXeu/Rin#92]
**描述你遇到的问题**

Pages 的 Functions 可同时部署前后端，是有别的什么因素考虑所以需要分开部署前后端呢？

**复现步骤**

**期望行为**

**截图**

**额外信息**

**Comment by OXeu** [comment]
1. 这个项目最开始是一个最传统的前后端分离的项目，后端最初是通过 docker 部署到自己的服务器上的，后来才改造成能够部署到 Cloudflare Workers 上，当时并不知道还能进一步迁移到 Functions
2. 现在应该也还能进行迁移？只不过目前主要精力还是集中在功能和细节的完善上，如果有人愿意帮忙研究如何迁移就更好了（欢迎 PR）
参照迁移文档应该能解决大部分问题 https://developers.cloudflare.com/pages/migrations/migrating-from-workers/

**Comment by SaintWe** [comment]
简单修改即：<https://developers.cloudflare.com/pages/functions/advanced-mode/>

**Comment by OXeu** [comment]
> 简单修改即：https://developers.cloudflare.com/pages/functions/advanced-mode/

简单看了一下，这种接入方法每次请求都会交给 workers 来处理，包括静态资源的请求也是，而 Functions 的是跟 Workers 使用相同的计费规则，每日 100k 次请求次数，总的来说相较于前后端分离 Pages 上的请求次数不计算来说更加不划算一些

**Comment by SaintWe** [comment]
是的，请求数会高一大截，抱歉没考虑到这个问题
