### ISSUE TITLE
[Help] 访问/sub/rss.xml提示404

### ISSUE THREAD

**Issue by ossplus** [OXeu/Rin#94]
**描述你遇到的问题**

**复现步骤**
1. 代码已升到最新并正常部署，前后端，访问正常；
2. R2里已生成了rss.xml等文件
3. 已按文档 设置路由/sub/*指向Rin Worker。
4. 访问 域名/sub/rss.xml时，提示404
Error 404
This object could not be viewed
You are not authorized to view this object
This object does not exist or is not publicly accessible at this URL. Check the URL of the object that you're looking for or contact the owner to enable Public access.

5. 但使用 S3_ACCESS_HOST 能访问到rss.xml文件
   S3_ACCESS_HOST/桶名/cache/rss.xml 

**期望行为**

**截图**

**额外信息**

**Comment by OXeu** [comment]
请检查一下使用 S3_ACCESS_HOST 末尾是否包含 `/` 目前路径为直接拼接的，末尾的 `/` 需要去除

**Comment by OXeu** [comment]
另外根据你的拼写方式，完整的 S3_ACCESS_HOST 应该包含"/桶名"，最终访问路径应形如 S3_ACCESS_HOST/cache/rss.xml

**Comment by ossplus** [comment]
问题解决，是我的拼接问题。
