### ISSUE TITLE
[Help] In the deploy doc, I have no idea how to config JWT_SECRET

### ISSUE THREAD

**Issue by freelixilong** [OXeu/Rin#95]

**Comment by ossplus** [comment]
https://github.com/OXeu/Rin/blob/main/docs/ENV.md
这个 文档里 有参数说明。
JWT_SECRET | JWT 认证所需密钥，可为常规格式的任意密码

**Comment by OXeu** [comment]
If you don't know what password to use for JWT_SECRET, just randomly generate one at https://www.avast.com/random-password-generator

**Comment by freelixilong** [comment]
> If you don't know what password to use for JWT_SECRET, just randomly generate one at https://www.avast.com/random-password-generator

OK, I'll try it
