### ISSUE TITLE
[Help] Referer not found

### ISSUE THREAD

**Issue by Pigeonszz** [OXeu/Rin#99]
**描述你遇到的问题**
前后端正常部署
已在pages设置自定义域
通过自定义域点击"github登录"后转到后端domain/user/github
显示   Referer not found
在使用pages自动分配的域名登录一切正常

**Comment by OXeu** [comment]
暂时没想到出现这个问题的原因，方便贴一下地址吗

**Comment by OXeu** [comment]
初步推测是由于使用的 google analysis 之类的产品导致 referrerpolicy 被修改导致的

**Comment by OXeu** [comment]
排查了一下，应该是页面返回的响应头中设置了 `referrer-policy: same-origin` 导致跳转时不携带 referrer 导致的，你可以先排查一下是不是什么 cloudflare 的配置的原因产生了这个响应头

**Comment by OXeu** [comment]
可能是设置了转换规则中的响应头规则，不过一般也不会去主动添加这个响应头
我现在主要怀疑是 Cloudflare Zaraz 为了隐私之类的方面引入这个响应头

**Comment by OXeu** [comment]
> 用了CF的Zaraz加载了Google Analytics 4， 但似乎无法解释为什么pages.dev域名可用

因为 Zaraz 只在你的选择的自己的域名上生效，所以 pages.dev 是不会应用你的 Zaraz 配置的，你可以先尝试禁用 Zaraz 再测试一下

**Comment by OXeu** [comment]
感觉 Zaraz 设置中的 `删除外部引用方` 是最有可能导致这个问题的原因，但是我测试了一遍没有复现出来

**Comment by OXeu** [comment]
临时的解决方案是在`转换规则` > `修改响应头` 添加如下规则
```
referrer-policy=strict-origin-when-cross-origin
```
![图片](https://github.com/OXeu/Rin/assets/36541432/6fbee6de-7c27-494d-baf1-89800426f772)

**Comment by moeacgx** [comment]
> 临时的解决方案是在`转换规则` > `修改响应头` 添加如下规则
> 
> ```
> referrer-policy=strict-origin-when-cross-origin
> ```
> 
> ![图片](https://private-user-images.githubusercontent.com/36541432/338151922-6fbee6de-7c27-494d-baf1-89800426f772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM4MTMsIm5iZiI6MTcxOTA2MzUxMywicGF0aCI6Ii8zNjU0MTQzMi8zMzgxNTE5MjItNmZiZWU2ZGUtN2MyNy00OTRkLWJhZjEtODk4MDA0MjZmNzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjNhNGQ0NjNmMDJhYmQ5OGVkZTJmNWMyNThjOGRjMTVjMGQxNDQwNjM4Y2U2Yjc5MjE4YTM5OGEwNWE1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOtVE7FmJt5MphKedh0FNEdRwdXbUqZSnQ0yW-lstYM)

我用的默认page域名点GitHub登录是跳转到//user/github  user前是两个//提示：NOT_FOUND  然后我手动删除一个/访问也是提示Referer not found

**Comment by OXeu** [comment]
> > 临时的解决方案是在`转换规则` > `修改响应头` 添加如下规则
> > ```
> > referrer-policy=strict-origin-when-cross-origin
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![图片](https://private-user-images.githubusercontent.com/36541432/338151922-6fbee6de-7c27-494d-baf1-89800426f772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM4MTMsIm5iZiI6MTcxOTA2MzUxMywicGF0aCI6Ii8zNjU0MTQzMi8zMzgxNTE5MjItNmZiZWU2ZGUtN2MyNy00OTRkLWJhZjEtODk4MDA0MjZmNzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjNhNGQ0NjNmMDJhYmQ5OGVkZTJmNWMyNThjOGRjMTVjMGQxNDQwNjM4Y2U2Yjc5MjE4YTM5OGEwNWE1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOtVE7FmJt5MphKedh0FNEdRwdXbUqZSnQ0yW-lstYM)
> 
> 我用的默认page域名点GitHub登录是跳转到//user/github user前是两个//提示：NOT_FOUND 然后我手动删除一个/访问也是提示Referer not found

两个 // 说明 Pages 的 API_URL 末尾多了一个 `/`,删掉以后重新部署

**Comment by moeacgx** [comment]
> > > 临时的解决方案是在`转换规则` > `修改响应头` 添加如下规则
> > > ```
> > > referrer-policy=strict-origin-when-cross-origin
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![图片](https://private-user-images.githubusercontent.com/36541432/338151922-6fbee6de-7c27-494d-baf1-89800426f772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjM4MTMsIm5iZiI6MTcxOTA2MzUxMywicGF0aCI6Ii8zNjU0MTQzMi8zMzgxNTE5MjItNmZiZWU2ZGUtN2MyNy00OTRkLWJhZjEtODk4MDA0MjZmNzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEzMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjNhNGQ0NjNmMDJhYmQ5OGVkZTJmNWMyNThjOGRjMTVjMGQxNDQwNjM4Y2U2Yjc5MjE4YTM5OGEwNWE1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOtVE7FmJt5MphKedh0FNEdRwdXbUqZSnQ0yW-lstYM)
> > 
> > 
> > 我用的默认page域名点GitHub登录是跳转到//user/github user前是两个//提示：NOT_FOUND 然后我手动删除一个/访问也是提示Referer not found
> 
> 两个 // 说明 Pages 的 API_URL 末尾多了一个 `/`,删掉以后重新部署

感谢！ 可以使用了
